# Generated by Django 6.0.4 on 2026-04-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='layout_style',
            field=models.CharField(choices=[('flex-row', 'Image on Right'), ('flex-row-reverse', 'Image on Left')], default='flex-row', help_text='Choose which side the image appears on', max_length=20),
        ),
    ]
