# Generated by Django 6.0.4 on 2026-04-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_herosection_layout_style'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'Hero Section', 'verbose_name_plural': 'Hero Section'},
        ),
        migrations.AlterField(
            model_name='herosection',
            name='description',
            field=models.TextField(help_text='A brief professional bio for the hero section'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='layout_style',
            field=models.CharField(choices=[('flex-row', 'Image on Right'), ('flex-row-reverse', 'Image on Left')], default='flex-row', help_text="Choose 'Image on Right' for the classic modern look.", max_length=20, verbose_name='Image Position'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='name',
            field=models.CharField(help_text='Your full name (e.g., David Thomas)', max_length=100),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='profile_image',
            field=models.ImageField(help_text='Upload a high-quality portrait (PNG or JPG)', upload_to='profile/'),
        ),
    ]
