# Generated by Django 6.0.4 on 2026-09-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_herosection_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutSection',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='HeroSection',
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectfeature',
            name='project',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicedetailimage',
            name='service_detail',
        ),
        migrations.RemoveField(
            model_name='servicefeature',
            name='service_detail',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='PortfolioCategory',
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectFeature',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceDetailImage',
        ),
        migrations.DeleteModel(
            name='ServiceDetail',
        ),
        migrations.DeleteModel(
            name='ServiceFeature',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='SkillCategory',
        ),
    ]
